"""Add todo_list and update todo_item

Revision ID: 3f88148c123d
Revises: e1637bff35f0
Create Date: 2025-12-28 03:44:00.473632

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f88148c123d'
down_revision: Union[str, Sequence[str], None] = 'e1637bff35f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo_items', sa.Column('list_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'todo_items', 'todo_lists', ['list_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'todo_items', type_='foreignkey')
    op.drop_column('todo_items', 'list_id')
    # ### end Alembic commands ###
